from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, JSON, ForeignKey, Text
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
import uuid
from app.database import Base

class Lyric(Base):
    __tablename__ = "lyrics"

    id              = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    title           = Column(String, nullable=False)
    writer_id       = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    # Cover art data
    cover_bg        = Column(String, default="#C6FF3D")
    cover_ink       = Column(String, default="#0E0E10")
    cover_emoji     = Column(String, default="🎤")
    cover_shape     = Column(String, default="rect")   # rect | blob | circle | burst

    # Metadata
    mood            = Column(JSON, default=list)        # ["heartbreak", "late night"]
    genre           = Column(String, nullable=False)
    bpm             = Column(Integer, nullable=True)
    key             = Column(String, nullable=True)
    tag             = Column(String, nullable=True)     # TRENDING | HOT | NEW | BIDDING | EXCLUSIVE ONLY | null

    # Content
    teaser          = Column(Text, nullable=False)      # public 2-line preview
    full_text       = Column(Text, nullable=False)      # locked until purchase
    ai_summary      = Column(Text, nullable=True)       # generated by Claude

    # Pricing
    price           = Column(Integer, nullable=False)   # non-exclusive price
    exclusive_price = Column(Integer, nullable=False)

    # Bidding
    bidding         = Column(Boolean, default=False)
    current_bid     = Column(Integer, nullable=True)
    bid_ends        = Column(DateTime, nullable=True)

    # Stats
    plays           = Column(Integer, default=0)
    saves           = Column(Integer, default=0)
    comments        = Column(Integer, default=0)
    sold_count      = Column(Integer, default=0)

    is_exclusive_sold = Column(Boolean, default=False)  # exclusive already purchased
    created_at      = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    writer   = relationship("User",    back_populates="lyrics",   foreign_keys=[writer_id])
    licenses = relationship("License", back_populates="lyric",    foreign_keys="License.lyric_id")
    bids     = relationship("Bid",     back_populates="lyric",    foreign_keys="Bid.lyric_id")
