"""initial

Revision ID: 5c25e04c6091
Revises: 
Create Date: 2026-05-09 23:52:47.409957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c25e04c6091'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('writer', 'buyer', name='userrole'), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('vibes', sa.JSON(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('lyrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('writer_id', sa.String(), nullable=False),
    sa.Column('cover_bg', sa.String(), nullable=True),
    sa.Column('cover_ink', sa.String(), nullable=True),
    sa.Column('cover_emoji', sa.String(), nullable=True),
    sa.Column('cover_shape', sa.String(), nullable=True),
    sa.Column('mood', sa.JSON(), nullable=True),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('teaser', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('exclusive_price', sa.Integer(), nullable=False),
    sa.Column('bidding', sa.Boolean(), nullable=True),
    sa.Column('current_bid', sa.Integer(), nullable=True),
    sa.Column('bid_ends', sa.DateTime(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('sold_count', sa.Integer(), nullable=True),
    sa.Column('is_exclusive_sold', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyrics_writer_id'), 'lyrics', ['writer_id'], unique=False)
    op.create_table('bids',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lyric_id', sa.String(), nullable=False),
    sa.Column('bidder_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'outbid', 'won', 'expired', name='bidstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lyric_id'], ['lyrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bids_bidder_id'), 'bids', ['bidder_id'], unique=False)
    op.create_index(op.f('ix_bids_lyric_id'), 'bids', ['lyric_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lyric_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('license_type', sa.Enum('non_exclusive', 'exclusive', name='licensetype'), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lyric_id'], ['lyrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_buyer_id'), 'licenses', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_licenses_lyric_id'), 'licenses', ['lyric_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('writer_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('lyric_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lyric_id'], ['lyrics.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_buyer_id'), 'threads', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_threads_writer_id'), 'threads', ['writer_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_threads_writer_id'), table_name='threads')
    op.drop_index(op.f('ix_threads_buyer_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_licenses_lyric_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_buyer_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_bids_lyric_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_bidder_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_lyrics_writer_id'), table_name='lyrics')
    op.drop_table('lyrics')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
