export const WRITERS = [
  {
    id: 'maya',
    handle: '@nooneatnight',
    name: 'Maya Reyes',
    emoji: '🌙',
    color: '#FF3D8A',
    bio: 'sad pop & late-night spirals. ATL → LA. comma usage is a vibe',
    vibes: ['heartbreak', 'late night', 'sad-girl pop'],
    sold: 142, followers: '12.4k', rating: 4.9, joined: '2023',
  },
  {
    id: 'jules',
    handle: '@phlegmatic',
    name: 'Jules Park',
    emoji: '🥀',
    color: '#2D52FF',
    bio: 'i write hooks for the chronically online. dms open for collabs',
    vibes: ['hyperpop', 'internet feelings', 'chaotic'],
    sold: 89, followers: '8.7k', rating: 4.8, joined: '2024',
  },
  {
    id: 'theo',
    handle: '@bigsigh',
    name: 'Theo Carrasco',
    emoji: '🌵',
    color: '#FF6B1A',
    bio: 'desert country boy. cowboy songs for sad bisexuals',
    vibes: ['country', 'folk', 'longing'],
    sold: 67, followers: '5.2k', rating: 4.9, joined: '2023',
  },
  {
    id: 'ari',
    handle: '@softlaunched',
    name: 'Ari Goldstein',
    emoji: '🍒',
    color: '#C6FF3D',
    bio: 'bedroom pop & soft launches. write me when ur situationship implodes',
    vibes: ['bedroom pop', 'situationship', 'soft'],
    sold: 203, followers: '21k', rating: 5.0, joined: '2022',
  },
  {
    id: 'devon',
    handle: '@gloryhourz',
    name: 'Devon Lee',
    emoji: '🪩',
    color: '#A24BFF',
    bio: 'disco renaissance. bring the bass i bring the bars',
    vibes: ['disco', 'dance pop', 'horny'],
    sold: 156, followers: '17.3k', rating: 4.7, joined: '2023',
  },
  {
    id: 'sam',
    handle: '@luckystrike',
    name: 'Sam Bennett',
    emoji: '🎰',
    color: '#FFD23F',
    bio: 'punk hooks for the unlucky. midwest emo apologist',
    vibes: ['pop punk', 'emo', 'gym hype'],
    sold: 44, followers: '3.1k', rating: 4.8, joined: '2025',
  },
];

export const LYRICS = [
  {
    id: 'velvet-headache',
    title: 'Velvet Headache',
    cover: { bg: '#FF3D8A', ink: '#0E0E10', emoji: '💊', shape: 'blob' },
    writer: 'maya',
    mood: ['heartbreak', 'late night'],
    genre: 'sad pop',
    bpm: 78, key: 'C minor',
    price: 240, exclusive: 1800,
    bidding: true, currentBid: 920, bidders: 7, bidEnds: '2d 14h',
    tag: 'TRENDING',
    teaser: "you call my name like it's a parking ticket\nfolded in your pocket, paid in pink",
    full: [
      "you call my name like it's a parking ticket",
      "folded in your pocket, paid in pink",
      "i was a velvet headache, you were leaving",
      "i don't sleep i just downgrade my dreams",
      "",
      "[chorus]",
      "soft, soft, soft, the way you ruin me",
      "you don't say sorry, you redecorate",
      "soft, soft, soft, the way i let you leave",
      "first thing in the morning, last thing on my plate",
    ],
    plays: '4.2k', saves: 891, comments: 42,
  },
  {
    id: 'parking-lot-messiah',
    title: 'PARKING LOT MESSIAH',
    cover: { bg: '#C6FF3D', ink: '#0E0E10', emoji: '⛪', shape: 'burst' },
    writer: 'jules',
    mood: ['anthem', 'chaotic'],
    genre: 'indie rock',
    bpm: 142, key: 'E major',
    price: 320, exclusive: 2400,
    bidding: false,
    tag: 'HOT',
    teaser: "praying to a 7-eleven\nwith a slurpee in my hand",
    full: [
      "praying to a 7-eleven",
      "with a slurpee in my hand",
      "got saved by a stranger's bumper sticker",
      "that said don't tread on me, man",
      "",
      "[chorus]",
      "PARKING LOT MESSIAH",
      "TELL ME WHAT YOU PAID FOR",
      "PARKING LOT MESSIAH",
      "I'LL BE WAITING IN THE BACK ROW",
    ],
    plays: '12.1k', saves: 2100, comments: 156,
  },
  {
    id: 'honey-im-static',
    title: "honey, im static",
    cover: { bg: '#2D52FF', ink: '#FFF8E7', emoji: '📺', shape: 'rect' },
    writer: 'ari',
    mood: ['bedroom pop', 'soft'],
    genre: 'bedroom pop',
    bpm: 88, key: 'G major',
    price: 180, exclusive: 1400,
    bidding: true, currentBid: 540, bidders: 4, bidEnds: '5d 02h',
    tag: 'NEW',
    teaser: "bluetooth heart, lowercase love\nyou took the dog, you left the rug",
    full: [
      "bluetooth heart, lowercase love",
      "you took the dog, you left the rug",
      "honey, i'm static between your stations",
      "tuning out, tuning in, tuning up",
    ],
    plays: '2.8k', saves: 612, comments: 28,
  },
  {
    id: 'big-teeth',
    title: 'BIG TEETH ENERGY',
    cover: { bg: '#A24BFF', ink: '#FFF8E7', emoji: '🦷', shape: 'blob' },
    writer: 'jules',
    mood: ['hyperpop', 'gym hype'],
    genre: 'hyperpop',
    bpm: 168, key: 'A minor',
    price: 420, exclusive: 3200,
    bidding: false,
    tag: 'EXCLUSIVE ONLY',
    teaser: "all bark, all bite, all bling\nbig teeth energy in the spring",
    full: ["all bark, all bite, all bling", "big teeth energy in the spring"],
    plays: '8.9k', saves: 1340, comments: 88,
  },
  {
    id: 'disco-for-one',
    title: 'Disco for One',
    cover: { bg: '#FFD23F', ink: '#0E0E10', emoji: '🪩', shape: 'circle' },
    writer: 'devon',
    mood: ['disco', 'lonely'],
    genre: 'synthwave',
    bpm: 124, key: 'F# minor',
    price: 280, exclusive: 2200,
    bidding: true, currentBid: 1100, bidders: 11, bidEnds: '14h 33m',
    tag: 'BIDDING',
    teaser: "i don't need a plus one\nthe mirror ball does the heavy lifting",
    full: ["i don't need a plus one", "the mirror ball does the heavy lifting"],
    plays: '6.3k', saves: 980, comments: 71,
  },
  {
    id: 'cold-plunge',
    title: 'Crying in the Cold Plunge',
    cover: { bg: '#FF6B1A', ink: '#0E0E10', emoji: '🧊', shape: 'rect' },
    writer: 'maya',
    mood: ['breakup', 'wellness'],
    genre: 'alt pop',
    bpm: 96, key: 'D minor',
    price: 220, exclusive: 1600,
    bidding: false,
    tag: 'TRENDING',
    teaser: "44 degrees and i'm finally feeling something\nwhich is to say, you",
    full: ["44 degrees and i'm finally feeling something", "which is to say, you"],
    plays: '5.1k', saves: 770, comments: 64,
  },
  {
    id: 'linen-suit',
    title: 'Linen Suit',
    cover: { bg: '#FFF8E7', ink: '#0E0E10', emoji: '👔', shape: 'blob' },
    writer: 'theo',
    mood: ['country', 'longing'],
    genre: 'country folk',
    bpm: 72, key: 'A major',
    price: 160, exclusive: 1200,
    bidding: false,
    tag: null,
    teaser: "wore my best linen suit\nto a funeral that wasn't yours",
    full: ["wore my best linen suit", "to a funeral that wasn't yours"],
    plays: '1.9k', saves: 380, comments: 22,
  },
  {
    id: 'algo',
    title: 'the algorithm hates me',
    cover: { bg: '#0E0E10', ink: '#C6FF3D', emoji: '👁️', shape: 'rect' },
    writer: 'jules',
    mood: ['internet feelings', 'late night'],
    genre: 'indie',
    bpm: 104, key: 'B minor',
    price: 200, exclusive: 1500,
    bidding: true, currentBid: 410, bidders: 3, bidEnds: '6d 18h',
    tag: 'NEW',
    teaser: "the algorithm hates me\nbut the algorithm is right",
    full: ["the algorithm hates me", "but the algorithm is right"],
    plays: '3.4k', saves: 522, comments: 31,
  },
  {
    id: 'run-it',
    title: 'RUN IT THRU AGAIN',
    cover: { bg: '#0E0E10', ink: '#FF3D8A', emoji: '💸', shape: 'burst' },
    writer: 'devon',
    mood: ['gym hype', 'flex'],
    genre: 'rap / trap',
    bpm: 140, key: 'F minor',
    price: 380, exclusive: 2800,
    bidding: false,
    tag: 'HOT',
    teaser: "run it thru again, run it thru again\ni count the racks like i'm counting the rain",
    full: ["run it thru again, run it thru again", "i count the racks like i'm counting the rain"],
    plays: '15.6k', saves: 3200, comments: 201,
  },
  {
    id: 'soft-launch',
    title: 'Soft Launch',
    cover: { bg: '#C6FF3D', ink: '#FF3D8A', emoji: '🌷', shape: 'circle' },
    writer: 'ari',
    mood: ['situationship', 'soft'],
    genre: 'bedroom pop',
    bpm: 92, key: 'E major',
    price: 200, exclusive: 1500,
    bidding: false,
    tag: null,
    teaser: "soft launch, hard fall\nyou tagged me in a sunset",
    full: ["soft launch, hard fall", "you tagged me in a sunset"],
    plays: '7.2k', saves: 1450, comments: 104,
  },
  {
    id: 'boy-anthem',
    title: 'Boy Anthem',
    cover: { bg: '#FF3D8A', ink: '#FFF8E7', emoji: '🎸', shape: 'blob' },
    writer: 'sam',
    mood: ['pop punk', 'breakup'],
    genre: 'pop punk',
    bpm: 156, key: 'G major',
    price: 240, exclusive: 1800,
    bidding: true, currentBid: 680, bidders: 9, bidEnds: '1d 04h',
    tag: 'BIDDING',
    teaser: "i'm not a boy anthem\ni'm a long voicemail you don't return",
    full: ["i'm not a boy anthem", "i'm a long voicemail you don't return"],
    plays: '4.8k', saves: 820, comments: 58,
  },
  {
    id: 'bluetooth-heart',
    title: 'Bluetooth Heart',
    cover: { bg: '#2D52FF', ink: '#C6FF3D', emoji: '💙', shape: 'circle' },
    writer: 'devon',
    mood: ['R&B', 'late night'],
    genre: 'R&B',
    bpm: 86, key: 'C# minor',
    price: 260, exclusive: 2000,
    bidding: false,
    tag: null,
    teaser: "bluetooth heart, low battery love\npairing with everyone, faithful to none",
    full: ["bluetooth heart, low battery love", "pairing with everyone, faithful to none"],
    plays: '3.7k', saves: 590, comments: 47,
  },
];

export const MOODS = [
  { key: 'heartbreak',    emoji: '💔', label: 'heartbreak' },
  { key: 'gym hype',      emoji: '🔥', label: 'gym hype' },
  { key: 'late night',    emoji: '🌙', label: 'late night' },
  { key: 'situationship', emoji: '🫠', label: 'situationship' },
  { key: 'flex',          emoji: '💸', label: 'flex' },
  { key: 'soft',          emoji: '☁️', label: 'soft' },
  { key: 'chaotic',       emoji: '🌀', label: 'chaotic' },
  { key: 'longing',       emoji: '🥀', label: 'longing' },
  { key: 'breakup',       emoji: '🚪', label: 'breakup' },
  { key: 'horny',         emoji: '🍑', label: 'horny longing' },
];

export const THREADS = [
  {
    id: 't1', writer: 'maya', lyric: 'velvet-headache', unread: 2,
    last: 'sent the alt bridge — let me know if it lands harder for u',
    when: '2m',
    messages: [
      { from: 'them', text: 'yo your snippet of velvet headache is unreal', when: 'tue 11:40am' },
      { from: 'me',   text: 'ahhh thank u 🥹 i can do an exclusive if u want', when: 'tue 11:42am' },
      { from: 'them', text: 'whats the diff between exclusive and non?', when: 'tue 11:43am' },
      { from: 'me',   text: 'exclusive = nobody else can ever release it. non-ex = i can sell to up to 3 ppl. exclusive is $1800, non $240', when: 'tue 11:45am' },
      { from: 'them', text: 'sent the alt bridge — let me know if it lands harder for u', when: '2m' },
    ],
  },
  {
    id: 't2', writer: 'jules', lyric: 'parking-lot-messiah', unread: 0,
    last: 'invoice goes out friday. ur a star ⭐',
    when: '1h',
    messages: [{ from: 'them', text: 'invoice goes out friday. ur a star ⭐', when: '1h' }],
  },
  {
    id: 't3', writer: 'ari', lyric: 'soft-launch', unread: 1,
    last: 'can we hop on a quick co-write? i hear a counterpoint',
    when: '4h',
    messages: [{ from: 'them', text: 'can we hop on a quick co-write? i hear a counterpoint', when: '4h' }],
  },
  {
    id: 't4', writer: 'devon', lyric: null, unread: 0,
    last: 'pulled up to the studio rn. send the topline pls',
    when: 'yest',
    messages: [{ from: 'them', text: 'pulled up to the studio rn. send the topline pls', when: 'yest' }],
  },
];

export function lyricById(id) { return LYRICS.find(l => l.id === id); }
export function writerById(id) { return WRITERS.find(w => w.id === id); }
